Feature/authentication views
diegosaul402/the_beer_logger pull request #3
Opened 2018-05-04 22:03 UTC by diegosaul402

## Before
![image](https://user-images.githubusercontent.com/14918730/39552050-2d9b32ea-4e2d-11e8-84ca-3b407105f95b.png)

## After

![image](https://user-images.githubusercontent.com/14918730/39655004-0b2a79fa-4fbd-11e8-81ae-d84044bd1679.png)

2018-05-07 18:25 UTC, jclopezdev requested changes

2018-05-07 18:25 UTC, jclopezdev commented on app/assets/stylesheets/components/_cards.scss
> +  line-height: 20px;
Please alphabetize your CSS properties 😃

2018-05-08 17:44 UTC, jnegrete approved these changes
LGTM!

2018-05-08 17:52 UTC, jclopezdev approved these changes
LGTM!!!!!!!!!!!!!

2018-05-08 17:53 UTC, dannharo commented on app/views/layouts/application.html.haml
> +        = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
use the `class: 'navbar-lik'` way, instead of  the *hash rocket way* `:class => 'navbar-link'`

2018-05-08 17:53 UTC, dannharo commented on app/views/layouts/application.html.haml
> +        \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
Delete commented code lines to keep clean your code

2018-05-08 17:53 UTC, dannharo commented on app/views/layouts/application.html.haml
> +        \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
the same for the line  `#31` too

2018-05-08 18:12 UTC, diegosaul402 commented on app/views/layouts/application.html.haml
> +        = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
great, done!

2018-05-08 18:12 UTC, diegosaul402 commented on app/views/layouts/application.html.haml
> +        \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
Done too

2018-05-08 18:40 UTC, jclopezdev reviewed
More comments 😬

2018-05-08 18:40 UTC, jclopezdev commented on app/views/devise/passwords/new.html.haml
> +        = f.submit "Reset password", class: 'btn blue waves-effect waves-light submit-button'
Use single quotes `'` instead of `"` in all the files for convention, what do you think?

2018-05-08 18:40 UTC, jclopezdev commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
The same thing @dannharo told you, use  content: 'text/html' way, instead of the hash rocket way :content => 'navbar-link'

2018-05-08 18:40 UTC, jclopezdev commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
The same thing @dannharo told you

2018-05-09 16:56 UTC, merged